version: 2

workflows:
  version: 2
  test:
    jobs:
      - run_tests
  deploy:
    jobs:
      - run_tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - run_deploy:
          requires:
            - run_tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
jobs:
  run_tests:
    docker:
      - image: cimg/python:3.7.11
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
      - run:
          name: Set up a local Solr with build's solr config.
          command: bash .circleci/setup_solr.sh
      - run:
          name: Test that we can get to the solr collection successfully.
          command: bash .circleci/test.sh
  run_deploy:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
      - run:
          name: Build configuration asset
          command: bash .circleci/build.sh
      - run:
          name: Deploy configuration asset to SolrCloud
          command: bash .circleci/deploy.sh
