name: Deploy

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Set up local Solr with build's solr config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/scripts/setup_solr.sh

      - name: Test Solr collection accessibility
        run: bash .github/scripts/test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Build configuration asset
        run: bash .github/scripts/build.sh

      - name: Deploy configuration asset to SolrCloud
        env:
          SOLR_USER: ${{ secrets.SOLR_USER }}
          SOLR_PASSWORD: ${{ secrets.SOLR_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: bash .github/scripts/deploy.sh
