name: Lint and Test

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Set up local Solr with build's solr config
        run: bash .github/scripts/setup_solr.sh

      - name: Test Solr collection accessibility
        run: bash .github/scripts/test.sh
